include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_web_libraries_in_flutter: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    library_private_types_in_public_api: true
    prefer_final_fields: true
    public_member_api_docs: true
